import sys

from pylo import log
import logging
#log.setLevel(logging.DEBUG)

sys.path.append('..')

import argparse
import pylo
import random

workloadsToCreateQuantity = 10000
targetHostname = '192.168.253.10'


target = pylo.Organization(1)
print("Loading Organization's data from API...")
# target.load_from_saved_credentials(hostname)
print("Done !")

connector = pylo.APIConnector.create_from_credentials_in_file(targetHostname)


workloadObject = {
    "name": "randomhere",
    "description": "generated by script",
    "hostname": "something random",
    "data_center": "somewhere on this planet",
    "os_id": "Linux",
    "os_detail": "Centos 7.1"

}

random.seed()
baseNumber = random.randint(0, 1000000)

print("Downloading labels infos from PCE...")
workloads_json = connector.objects_label_get()
target.LabelStore.loadLabelsFromJson(workloads_json)
print("done!")

print("Downloading workloads infos from PCE...")
workloads_json = connector.objects_workload_get()
print("done!")


print("Organisation Statistics:\n", target.stats_to_str())


for i in range(0, workloadsToCreateQuantity):
    wkl_hostname = 'rand-' + str(i + baseNumber)
    print("-  Workload hostname will be '" + wkl_hostname + "' (#" + str(i+1) + " of " + str(workloadsToCreateQuantity)+ ")")
    workloadObject['name'] = wkl_hostname
    workloadObject['hostname'] = wkl_hostname

    loc_label = list(target.LabelStore.locationLabels.values())[random.randint(0, target.LabelStore.count_location_labels()-1)]
    env_label = list(target.LabelStore.environmentLabels.values())[random.randint(0, target.LabelStore.count_environment_labels()-1)]
    app_label = list(target.LabelStore.applicationLabels.values())[random.randint(0, target.LabelStore.count_application_labels()-1)]
    role_label = list(target.LabelStore.roleLabels.values())[random.randint(0, target.LabelStore.count_role_labels()-1)]

    print("    Location label will be: " + loc_label.name)
    print("    Environment label will be: " + env_label.name)
    print("    Application label will be: " + app_label.name)
    print("    Role label will be: " + role_label.name)

    labels = [ {"href": loc_label.href}, {"href": env_label.href}, {"href": app_label.href}, {"href": role_label.href} ]

    workloadObject['labels'] = labels

    connector.objects_workload_create_single_unmanaged(workloadObject)




